### ISSUE TITLE
How to access in Docker

### ISSUE THREAD

**Issue by seki-shinnosuke** [julien-pal/node-red-contrib-grpc#27]
I would like to know how to use Node-Red built using Docker.

Dockerfile
```
FROM nodered/node-red:3.1.9

COPY ./files/node-red/package.json /data/package.json
RUN npm install --unsafe-perm --no-update-notifier --no-fund --only=production
RUN npm install node-red-contrib-grpc

COPY ./files/node-red/settings.js /data/settings.js
COPY ./files/node-red/flows_cred.json /data/flows_cred.json
COPY ./files/node-red/flows.json /data/flows.json

EXPOSE 1881 5001
```

docker-compose
```
  node-red:
    build:
      context: ./docker
      dockerfile: Dockerfile-nodered
    image: nodered:1.0
    container_name: nodered
    networks:
      - xxxx
    ports:
      - "1881:1881"
      - "5001:5001"
```
<img width="896" alt="2024-06-23 3 04 56" src="https://github.com/julien-pal/node-red-contrib-grpc/assets/90810155/8e9c455f-18e7-4811-8e01-67b5f0b4e118">

```
% grpcurl -plaintext localhost:5001 list
Failed to dial target host "localhost:5001": context deadline exceeded
```

Calls from the dashboard succeed, but calls from localhost fail.
